apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-app
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: merchant-frontend
        image: lian1280/ceramicraft-merchant-frontend:latest
     