apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-micro
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/NUS-ISS-Agile-Team/ceramicraft-argocd-deploy.git
    targetRevision: HEAD
    path: backend
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {prune: true, selfHeal: true}
