apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-app          
spec:
  replicas: 1           
  selector:
    matchLabels: &labels
      app: vue-app
  template:
    metadata:
      labels: *labels
    spec:
      containers:
      - name: nginx
        image: nginx:1.25-alpine         
        ports:
        - containerPort: 80
          name: http
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5