apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web
spec:
  replicas: 1
  selector:
    matchLabels: { app: nginx-web }
  template:
    metadata:
      labels: { app: nginx-web }
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests: { memory: "64Mi", cpu: "50m" }
          limits:   { memory: "128Mi", cpu: "100m" }
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-web
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30090     
  selector:
    app: nginx-web
