apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-ms-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/lianjin/git-ops.git
    targetRevision: HEAD
    path: charts
    helm:
      valueFiles:
        -  ../helm_backend/values/user-ms.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true